export {
  ANALYTICS_EVENTS,
  ANALYTICS_EVENT_CATALOG,
  EVENT_CATEGORY,
  GA4_EVENTS,
  META_EVENTS,
  PAGE_CONTENT_GROUPS,
  getContentGroup,
  type AnalyticsEventName,
  type ConsultationSource,
  type EventCategory,
  type ServiceSlug,
  type SocialPlatform,
} from "./events";

export {
  analyticsConfig,
  hasAnalytics,
  useGtmHub,
  initAnalyticsScripts,
  track,
  trackPageView,
  trackScrollDepth,
  trackNavigationClick,
  trackCtaClick,
  trackConsultationModalOpen,
  trackConsultationModalClose,
  trackConsultationFormStart,
  trackConsultationLead,
  trackConsultationFormError,
  trackCalculatorStarted,
  trackCalculatorAreaUpdated,
  trackCalculatorUnitChanged,
  trackCalculatorPackageSelect,
  trackCalculatorEstimateViewed,
  trackCalculatorReset,
  trackSignInStart,
  trackSignInComplete,
  trackDashboardOpen,
  trackOutboundContact,
  trackSocialClick,
  trackFaqExpand,
  trackViewServiceInterest,
  type TrackParams,
} from "./core";
