export {
  ANALYTICS_EVENTS,
  ANALYTICS_EVENT_CATALOG,
  CONSULTATION_FORM_NAME,
  EVENT_CATEGORY,
  GA4_EVENTS,
  META_EVENTS,
  PAGE_CONTENT_GROUPS,
  formServiceToInterest,
  getContentGroup,
  getPageType,
  isBookFreeConsultationLabel,
  sourceToCtaLocation,
  type AnalyticsEventName,
  type ConsultationSource,
  type CtaLocation,
  type EventCategory,
  type PageType,
  type ServiceSlug,
  type SocialPlatform,
} from "./events";

export {
  CORE_SERVICE_INTERESTS,
  FOOTER_SERVICE_LINKS,
  SPECIALIZED_SERVICE_CARDS,
} from "./serviceCatalog";

export {
  analyticsConfig,
  hasAnalytics,
  useGtmHub,
  initAnalyticsScripts,
  initDataLayer,
  pushGtmEvent,
  pushPageType,
  track,
  trackPageView,
  trackScrollDepth,
  trackNavigationClick,
  trackCtaClick,
  trackConsultationModalOpen,
  trackConsultationModalClose,
  trackConsultationFormStart,
  trackConsultationLead,
  trackConsultationFormError,
  trackConsultationCtaClick,
  trackServiceInterestClick,
  trackPhoneClick,
  trackWhatsAppClick,
  trackCalculatorStarted,
  trackCalculatorAreaUpdated,
  trackCalculatorUnitChanged,
  trackCalculatorPackageSelect,
  trackCalculatorEstimateViewed,
  trackCalculatorReset,
  trackSignInStart,
  trackSignInComplete,
  trackDashboardOpen,
  trackOutboundContact,
  trackSocialClick,
  trackFaqExpand,
  trackViewServiceInterest,
  type TrackParams,
} from "./core";

export {
  analyticsDataAttributes,
  analyticsProps,
  buttonIdFromLabel,
  consultationSubmitId,
  consultationTriggerId,
  ctaTriggerId,
  inputAnalyticsId,
  navLinkId,
  slugifyButtonLabel,
  slugifyServiceInterest,
} from "./ids";
